version: '3'
services:
  back:
    build: .
    ports:
     - "8080:8080"
    environment:
     - JAVA_OPTS=-Dspring.datasource.url=jdbc:mysql://mysql:3306/callcenter
    depends_on:
     - 'mysql'
  mysql:
    image: 'mysql:5.7'
    expose:
      - '3306'
    environment:
      - MYSQL_DATABASE=callcenter
      - MYSQL_USER=callcenter
      - MYSQL_PASSWORD=callcenterpw
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    logging:
        driver: none